### ISSUE TITLE
Not able to `npm run dev` due to `Error: got multiple ambig for api:declarativeNetRequest: 2`

### ISSUE THREAD

**Issue by chybie** [GoogleChrome/developer.chrome.com#1346]
**Describe the bug**
Failed to `npm run dev` due to `Error: got multiple ambig for api:declarativeNetRequest: 2`.

**To Reproduce**
1. Download and setup repo
2. `npm run dev`

**Expected behavior**
Able to `npm run dev`

**Logs**
```
Error: got multiple ambig for api:declarativeNetRequest: 2
        at Features.#singleResolve (/developer.chrome.com/node_modules/chrome-types-helpers/lib-gen-main.cjs:1079:13)
        at Features.query (/developer.chrome.com/node_modules/chrome-types-helpers/lib-gen-main.cjs:1119:41)
        at JSONSchemaParser.parse (/developer.chrome.com/node_modules/chrome-types-helpers/lib-gen-main.cjs:2171:47)
        at /developer.chrome.com/node_modules/chrome-types-helpers/lib-gen-main.cjs:2749:26
        at Array.forEach (<anonymous>)
        at Object.prepareNamespaces (/developer.chrome.com/node_modules/chrome-types-helpers/lib-gen-main.cjs:2746:11)
        at async module.exports (/developer.chrome.com/site/_data/chromeApiNamespaces.js:50:15)
        at async TemplateData.getDataValue (/developer.chrome.com/node_modules/@11ty/eleventy/src/TemplateData.js:385:23)
        at async TemplateData.getAllGlobalData (/developer.chrome.com/node_modules/@11ty/eleventy/src/TemplateData.js:228:18)
        at async TemplateData.getData (/developer.chrome.com/node_modules/@11ty/eleventy/src/TemplateData.js:255:24)
```

**Desktop (please complete the following information):**
 - OS: Mac BigSur

**Comment by samthor** [comment]
Sorry, fixed by #1345.
