### ISSUE TITLE
Presubmit checks for bad hero image URLs

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/developer.chrome.com#3029]
As we encountered with the issue resolved by https://github.com/GoogleChrome/developer.chrome.com/pull/3028, if there's an invalid hero image tag in a post's `frontmatter` metadata, the 11ty build will error out.

We need to check for this as part of our presubmit process to avoid this happening again.

```
Error writing templates: (more in DEBUG output)
> Having trouble writing template: false

`TemplateWriterWriteError` was thrown
> (./site/_includes/layouts/blog-post.njk) [Line 11, Column 3]
  EleventyShortcodeError: Error with Nunjucks shortcode `Img`

`Template render error` was thrown
> ERROR IN ./site/ru/blog/new-in-devtools-103/index.md, IMG mage/dPDCek3EhZgLQPGtEG3y0fTn4v82/8mwEVUbzEuE8Xut2AZrU.jpg: invalid src provided (was this added via the uploader?)

`Template render error` was thrown:
    Error: ERROR IN ./site/ru/blog/new-in-devtools-103/index.md, IMG mage/dPDCek3EhZgLQPGtEG3y0fTn4v82/8mwEVUbzEuE8Xut2AZrU.jpg: invalid src provided (was this added via the uploader?)
        at Object.returnedFunction (/workspace/node_modules/webdev-infra/shortcodes/Img.js:85:13)
        at Object.<anonymous> (/workspace/node_modules/@11ty/eleventy/src/BenchmarkGroup.js:30:26)
        at ShortcodeFunction.run (/workspace/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:138:27)
        at b_content (eval at _compile (/workspace/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:102:63)
        at eval (eval at _compile (/workspace/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:149:86)
        at eval (eval at _compile (/workspace/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:87:1)
        at eval (eval at _compile (/workspace/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:83:1)
        at fn (/workspace/node_modules/a-sync-waterfall/index.js:26:24)
        at /workspace/node_modules/a-sync-waterfall/index.js:66:22
        at executeSync (/workspace/node_modules/a-sync-waterfall/index.js:8:15)
```

**Comment by jeffposnick** [comment]
Looking into this more, we didn't catch this in our presubmit checks or staging build because the issue only existing in an `/ru/` translation, and we explicitly skip anything other than `/en/` for both of those checks:

- https://app.netlify.com/sites/developer-chrome-com/deploys/62a884c01d54e300089555b2#L73
- https://github.com/GoogleChrome/developer.chrome.com/runs/6880701967?check_suite_focus=true#step:11:11

I'd propose that we change at least our "Lint, test and build" GitHub Action so that it runs against the full set of translations, not just `/en/`.
