### ISSUE TITLE
Partial build failing

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/developer.chrome.com#4159]
**Describe the bug**

Build fails when using this `.env` to speed up build.

## `.env` file

```
# Ignore ALL /docs/
#ELEVENTY_IGNORE_DOCS=true

# Only ignore /docs/android/
ELEVENTY_IGNORE_ANDROID=true

# Only ignore /docs/apps/
ELEVENTY_IGNORE_APPS=true

# Only ignore /docs/devtools/
#ELEVENTY_IGNORE_DEVTOOLS=true

# Only ignore /docs/extensions/
ELEVENTY_IGNORE_EXTENSIONS=true

# Only ignore /docs/handbook/
ELEVENTY_IGNORE_HANDBOOK=true

# Only ignore /docs/lighthouse/
ELEVENTY_IGNORE_LIGHTHOUSE=true

# Only ignore /docs/multidevice/
ELEVENTY_IGNORE_MULTIDEVICE=true

# Only ignore /docs/native-client/
ELEVENTY_IGNORE_NACL=true

# Only ignore /docs/privacy-sandbox/
ELEVENTY_IGNORE_PRIVACY_SANDBOX=true

# Only ignore /docs/versionhistory/
ELEVENTY_IGNORE_VERSIONHISTORY=true

# Only ignore /docs/webstore/
ELEVENTY_IGNORE_WEBSTORE=true

# Only ignore /docs/workbox/
ELEVENTY_IGNORE_WORKBOX=true

# Ignore BLOG /blog/
ELEVENTY_IGNORE_BLOG=true
```

## Error message

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering njk template ./site/en/_partials/devtools/engineering-blog.md (via TemplateContentRenderError)
[11ty] 2. (./site/en/_partials/devtools/engineering-blog.md)
[11ty]   TypeError: Cannot read properties of undefined (reading 'length') (via Template render error)
[11ty]
[11ty] Original error stack trace: Template render error: (./site/en/_partials/devtools/engineering-blog.md)
[11ty]   TypeError: Cannot read properties of undefined (reading 'length')
[11ty]     at Object._prettifyError (/Users/jakearchibald/dev/developer.chrome.com/node_modules/nunjucks/src/lib.js:36:11)
[11ty]     at /Users/jakearchibald/dev/developer.chrome.com/node_modules/nunjucks/src/environment.js:563:19
[11ty]     at Template.root [as rootRenderFunc] (eval at _compile (/Users/jakearchibald/dev/developer.chrome.com/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:106:3)
[11ty]     at Template.render (/Users/jakearchibald/dev/developer.chrome.com/node_modules/nunjucks/src/environment.js:552:10)
[11ty]     at /Users/jakearchibald/dev/developer.chrome.com/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:485:14
[11ty]     at new Promise (<anonymous>)
[11ty]     at /Users/jakearchibald/dev/developer.chrome.com/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:484:14
[11ty]     at /Users/jakearchibald/dev/developer.chrome.com/node_modules/@11ty/eleventy/src/Engines/Markdown.js:73:47
[11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11ty]     at async Template._render (/Users/jakearchibald/dev/developer.chrome.com/node_modules/@11ty/eleventy/src/TemplateContent.js:432:22)
[11ty] Benchmark    202ms  15%     1× (Data) `./site/_data/chromeApiNamespaces.js`
[11ty] Wrote 0 files in 1.07 seconds (v1.0.1)
ERROR: "eleventy" exited with 1.
```

**Comment by matthiasrohmer** [comment]
It seems as if `ELEVENTY_IGNORE_BLOG=true` which adds `'site/**/blog/**/*'` to the .eleventyignore also matches `./site/en/_partials/devtools/engineering-blog.md`.
