### ISSUE TITLE
could not fin URL 

### ISSUE THREAD

**Issue by ersenbasaransen** [GoogleChrome/developer.chrome.com#601]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
npm run elevent give a lot of "could not fin URL" erros.

**To Reproduce**
1. npm run dev

**Screenshots**
![image](https://user-images.githubusercontent.com/1652123/113482677-6aabe980-94a8-11eb-8986-8eb32e905333.png)

and more ...

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by dotproto** [comment]
@samthor, any thoughts on how best to tackle this?

**Comment by samthor** [comment]
This is somewhat intended for e.g., `native-client`, because we don't build it by default (it's pretty large).

On my build I see this:

```
Could not find URL: /en/docs/native-client/
Could not find URL: /en/docs/extensions/mv3/background_migration/
Could not find URL: /en/docs/extensions/mv3/migrating_to_manifest_v3/
Could not find URL: /en/docs/extensions/mv2/migrating_to_service_workers/
Could not find URL: /en/docs/extensions/mv2/migrating_to_manifest_v3/
Could not find URL: /en/docs/multidevice/webview/
Could not find URL: /en/docs/webstore/webstore_api/
```

There might be something about using Windows, @ersenbasaransen, which is causing the problem. Does the majority of the site build and load fine?

**Comment by cary-mao** [comment]
I also encountered this problem.   
```
Could not find URL: \en\docs\devtools\
Could not find URL: \en\docs\extensions\
Could not find URL: \en\docs\webstore\
```
and more.  My os is Window10, too. Does it not support Window?
When I visited the url `http://localhost:8080/en/docs/`, it throwed an error as follow:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:375:7)
    at notFoundHandler (E:\main\source_code\developer.chrome.com-main\server\not-found.js:42:23)
    at Layer.handle [as handle_request] (E:\main\source_code\developer.chrome.com-main\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\main\source_code\developer.chrome.com-main\node_modules\express\lib\router\index.js:317:13)
    at E:\main\source_code\developer.chrome.com-main\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\main\source_code\developer.chrome.com-main\node_modules\express\lib\router\index.js:335:12)
    at next (E:\main\source_code\developer.chrome.com-main\node_modules\express\lib\router\index.js:275:10)
    at replacedHandler (E:\main\source_code\developer.chrome.com-main\server\unique-redirect.js:302:18)
    at E:\main\source_code\developer.chrome.com-main\server\unique-redirect.js:314:30
```
It looks like a path handling error.

**Comment by samthor** [comment]
This is probably a Windows error.
