### ISSUE TITLE
Error message: "No translations for: i18n.authors.<authorname>.title" on npm run dev

### ISSUE THREAD

**Issue by theoffbeatdoc** [GoogleChrome/developer.chrome.com#6377]
I have found a similar past issue which has been closed as solved. But the solution there does not work in my case and I feel this is a bug that is not related to spaces.

**Describe the bug**
After having followed the setup instructions, I'm trying to run ´npm run dev´ but it fails with this error:

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] No translations for: i18n.authors.timstatler.title (via Error)
[11ty]
[11ty] Original error stack trace: Error: No translations for: i18n.authors.timstatler.title
[11ty]     at I18nDictionary.get (H:\GitHub\theoffbeatdoc\developer.chrome.com\node_modules\webdev-infra\utils\i18nDictionary.js:84:13)
[11ty]     at I18nFilter.filter (H:\GitHub\theoffbeatdoc\developer.chrome.com\node_modules\webdev-infra\filters\i18n.js:52:29)
[11ty]     at H:\GitHub\theoffbeatdoc\developer.chrome.com\site\en\authors\authors.11tydata.js:24:9
[11ty]     at Array.sort (<anonymous>)
[11ty]     at Object.before (H:\GitHub\theoffbeatdoc\developer.chrome.com\site\en\authors\authors.11tydata.js:23:22)
[11ty]     at Pagination._resolveItems (H:\GitHub\theoffbeatdoc\developer.chrome.com\node_modules\@11ty\eleventy\src\Plugins\Pagination.js:175:37)        
[11ty]     at Pagination.setData (H:\GitHub\theoffbeatdoc\developer.chrome.com\node_modules\@11ty\eleventy\src\Plugins\Pagination.js:96:26)
[11ty]     at new Pagination (H:\GitHub\theoffbeatdoc\developer.chrome.com\node_modules\@11ty\eleventy\src\Plugins\Pagination.js:19:10)
[11ty]     at Template.getTemplates (H:\GitHub\theoffbeatdoc\developer.chrome.com\node_modules\@11ty\eleventy\src\Template.js:724:21)
[11ty]     at TemplateMap.initDependencyMap (H:\GitHub\theoffbeatdoc\developer.chrome.com\node_modules\@11ty\eleventy\src\TemplateMap.js:288:41)
[11ty] Wrote 0 files in 43.96 seconds (v1.0.2)
ERROR: "eleventy" exited with 1.
```

I FOUND A SIMILAR ISSUE HERE https://github.com/GoogleChrome/webdev-infra/issues/66#issue-1637281788 WHICH HAS BEEN CLOSED AS COMPLETED. There @supermoos pointed out that it "seems the project doesn't like being run from a folder with spaces in". But that is not the case here. My folder path has no spaces in it and I've tried cloning the repo in several other folders. So, I guess the bug is not rooted in the cause mentioned in the earlier issue.

**To Reproduce**
clone the repo, run `npm ci` and then run `npm run dev`, error appears.

**Expected behavior**
Start a local server to preview the site.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [I'm having this error in my terminal even before the localhost starts.]
 - Version [Node.js v18.16.0]

**Additional context**

**Comment by matthiasrohmer** [comment]
https://github.com/GoogleChrome/webdev-infra/issues/66#issue-1637281788 was indeed about spaces in the file path and has been fixed.

Your issue is likely coming from the fact you are in a Windows environment, which this project does not support. A workaround is using the [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install).

**Comment by theoffbeatdoc** [comment]
Oh I see. Thanks @matthiasrohmer for clarifying this.
